rootfs: don't overwrite dot-config_status in apply_dot-config
/etc/init.d/dot-config can save information e.g. that it failed to get
dot-config form the given URL. However, apply_dot-config called from
/etc/init.d/dot-config overwrites this information by the result of checking
the dot-config. The checking of the dot-config has to be done also in
apply_dot-config, because the webinterface writes down changed dot-config and
executes only apply_dot-config.

Signed-off-by: Adam Wujek <adam.wujek@cern.ch>

diff --git a/userspace/rootfs_override/wr/bin/apply_dot-config b/userspace/rootfs_override/wr/bin/apply_dot-config
--- a/userspace/rootfs_override/wr/bin/apply_dot-config
+++ b/userspace/rootfs_override/wr/bin/apply_dot-config
@@ -22,33 +22,37 @@ copy_conf() {
     done
 }
 
-#check if config is local
+# check if config is local, used by webinterface
 if [ "$1" == "local_config" ]; then
-	# remove source information in case previous config was received from
-	# network
-	rm "$tmpdir"/dot-config_*
-	echo "local" > "$tmpdir"/dot-config_source
-fi
+    # remove source information in case previous config was received from
+    # network
+    rm "$tmpdir"/dot-config_*
+    echo "local" > "$tmpdir"/dot-config_source
 
-# Check and complain, but we need to edit some files even if unconfigured.
-if [ -f /wr/etc/dot-config ]; then
-    source /wr/etc/dot-config
-    ret_source=$?
-    /wr/bin/wrs_checkcfg /wr/etc/dot-config /wr/etc/Kconfig
-    ret_check=$?
-    configured=true
-    if [ $ret_source != 0 ] || [ $ret_check != 0 ]; then
-	# errors in local dot-config
-	echo "check_error" > "$tmpdir"/dot-config_status
-	echo "Errors found in local dot-config!!!" >& 2
+    # Check and complain
+    if [ -f /wr/etc/dot-config ]; then
+	source /wr/etc/dot-config
+	ret_source=$?
+	/wr/bin/wrs_checkcfg /wr/etc/dot-config /wr/etc/Kconfig
+	ret_check=$?
+	configured=true
+	if [ $ret_source != 0 ] || [ $ret_check != 0 ]; then
+	    # errors in local dot-config
+	    echo "check_error" > "$tmpdir"/dot-config_status
+	    echo "Errors found in local dot-config!!!" >& 2
+	else
+	    echo "config_ok" > "$tmpdir"/dot-config_status
+	fi
     else
-	echo "config_ok" > "$tmpdir"/dot-config_status
+	echo "No /wr/etc/dot-config to use" >& 2
+	echo "no_config" > "$tmpdir"/dot-config_source
+	echo "config_error" > "$tmpdir"/dot-config_status
+	configured=false
     fi
-else
-    echo "No /wr/etc/dot-config to use" >& 2
-    echo "no_config" > "$tmpdir"/dot-config_source
-    echo "config_error" > "$tmpdir"/dot-config_status
-    configured=false
+elif [ -f /wr/etc/dot-config ]; then
+    # if config was not touched by webinterface simply source it, the check was
+    # done by /etc/init.d/dot-config
+    source /wr/etc/dot-config
 fi
 
 ##### Actual configuration actions start here.
