configuration: allow ppsi.conf to be downloaded at boot
The new Kconfig option allows dowloading ppsi.conf at boot time, from
TFTP or otherwise.  The filename in the URL can include IPADDR and/or
MACADDR, so the same configuration string can be used to set up a
batch of switches with different configurations.

Signed-off-by: Alessandro Rubini <rubini@gnudd.com>

diff --git a/userspace/rootfs_override/wr/bin/apply_dot-config b/userspace/rootfs_override/wr/bin/apply_dot-config
--- a/userspace/rootfs_override/wr/bin/apply_dot-config
+++ b/userspace/rootfs_override/wr/bin/apply_dot-config
@@ -95,6 +95,50 @@ if [ "$CONFIG_PTP_PORT_PARAMS" = "y" ]; then
     /wr/bin/assembly_ppsi_conf.sh
 elif [ "$CONFIG_PTP_CUSTOM" = "y" ]; then
     cp "$CONFIG_PTP_CUSTOM_FILENAME" /wr/etc/ppsi.conf
+elif [ "$CONFIG_PTP_REMOTE_CONF" = "y" ]; then
+
+    # Warning: code below copied from /etc/init.d/dot-config.
+
+    tmpconfig=/tmp/ppsi-config
+
+    # replace IPADDR and MACADDR, to have a device-specific name
+    macaddr=$(cat /sys/class/net/eth0/address)
+    ipaddr=$(ifconfig eth0 | grep inet | cut -d: -f 2 | cut '-d '  -f 1)
+    if [ -z "$ipaddr" ]; then
+	# if no IP address available from barebox try to get IP from old dot-config
+	# /etc/init.d/network will run later again
+	/etc/init.d/network
+	ipaddr=$(ifconfig eth0 | grep inet | cut -d: -f 2 | cut '-d '  -f 1)
+    fi
+    URL=$(echo $CONFIG_PTP_CONF_URL | \
+	sed -e s/MACADDR/$macaddr/ -e s/IPADDR/$ipaddr/)
+    # split the parts, as we need to handle tftp by hand
+    proto=$(echo $URL | cut -d: -f 1)
+    host=$(echo $URL | cut -d/ -f 3)
+    filename=$(echo $URL | cut -d/ -f 4-)
+
+    # save proto, host and filename of dot-config, to be used by SNMPd
+    echo "$proto" > "$tmpdir"/dot-config_proto
+    echo "$host" > "$tmpdir"/dot-config_host
+    echo "$filename" > "$tmpdir"/dot-config_filename
+
+    rm -f $tmpconfig
+    case $proto in
+	http|ftp)
+	    wget $URL -O $tmpconfig
+	    ;;
+	tftp)
+	    tftp -g -r "$filename" -l $tmpconfig $host
+	    ;;
+	*)
+	    echo "Invalid URL for ppsi.conf: \"$URL\"" >& 2
+	    ;;
+    esac
+    if [ -f $tmpconfig ]; then
+	    # copy it in place to use the new file (unless it is identical)
+	    cmp -s $tmpconfig /wr/etc/ppsi.conf || \
+		cp $tmpconfig /wr/etc/ppsi.conf
+    fi
 else
     # no valid PTP option keep ppsi.conf with old postfix
     echo "No valid PTP option in dot-config!"
